package org.dexterity.darueira.azimuteerp.monolith.quarkus.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganizationDomainAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationDomainAllPropertiesEquals(OrganizationDomain expected, OrganizationDomain actual) {
        assertOrganizationDomainAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganizationDomainAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationDomainAllUpdatablePropertiesEquals(OrganizationDomain expected, OrganizationDomain actual) {
        assertOrganizationDomainUpdatableFieldsEquals(expected, actual);
        assertOrganizationDomainUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationDomainAutoGeneratedPropertiesEquals(OrganizationDomain expected, OrganizationDomain actual) {
        assertThat(expected)
            .as("Verify OrganizationDomain auto generated properties")
            .satisfies(e -> assertThat(e.id).as("check id").isEqualTo(actual.id));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationDomainUpdatableFieldsEquals(OrganizationDomain expected, OrganizationDomain actual) {
        assertThat(expected)
            .as("Verify OrganizationDomain relevant properties")
            .satisfies(e -> assertThat(e.domainAcronym).as("check domainAcronym").isEqualTo(actual.domainAcronym))
            .satisfies(e -> assertThat(e.name).as("check name").isEqualTo(actual.name))
            .satisfies(e -> assertThat(e.isVerified).as("check isVerified").isEqualTo(actual.isVerified))
            .satisfies(e -> assertThat(e.businessHandlerClazz).as("check businessHandlerClazz").isEqualTo(actual.businessHandlerClazz))
            .satisfies(e -> assertThat(e.activationStatus).as("check activationStatus").isEqualTo(actual.activationStatus));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationDomainUpdatableRelationshipsEquals(OrganizationDomain expected, OrganizationDomain actual) {
        assertThat(expected)
            .as("Verify OrganizationDomain relationships")
            .satisfies(e -> assertThat(e.organization).as("check organization").isEqualTo(actual.organization));
    }
}
