package de.org.dexterity.azimuteerp.monolith.quarkus.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationAllPropertiesEquals(Organization expected, Organization actual) {
        assertOrganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationAllUpdatablePropertiesEquals(Organization expected, Organization actual) {
        assertOrganizationUpdatableFieldsEquals(expected, actual);
        assertOrganizationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationAutoGeneratedPropertiesEquals(Organization expected, Organization actual) {
        assertThat(expected)
            .as("Verify Organization auto generated properties")
            .satisfies(e -> assertThat(e.id).as("check id").isEqualTo(actual.id));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationUpdatableFieldsEquals(Organization expected, Organization actual) {
        assertThat(expected)
            .as("Verify Organization relevant properties")
            .satisfies(e -> assertThat(e.acronym).as("check acronym").isEqualTo(actual.acronym))
            .satisfies(e -> assertThat(e.businessCode).as("check businessCode").isEqualTo(actual.businessCode))
            .satisfies(e -> assertThat(e.hierarchicalLevel).as("check hierarchicalLevel").isEqualTo(actual.hierarchicalLevel))
            .satisfies(e -> assertThat(e.name).as("check name").isEqualTo(actual.name))
            .satisfies(e -> assertThat(e.description).as("check description").isEqualTo(actual.description))
            .satisfies(e -> assertThat(e.businessHandlerClazz).as("check businessHandlerClazz").isEqualTo(actual.businessHandlerClazz))
            .satisfies(
                e -> assertThat(e.mainContactPersonDetails).as("check mainContactPersonDetails").isEqualTo(actual.mainContactPersonDetails)
            )
            .satisfies(
                e ->
                    assertThat(e.technicalEnvironmentsDetails)
                        .as("check technicalEnvironmentsDetails")
                        .isEqualTo(actual.technicalEnvironmentsDetails)
            )
            .satisfies(
                e ->
                    assertThat(e.commonCustomAttributesDetails)
                        .as("check commonCustomAttributesDetails")
                        .isEqualTo(actual.commonCustomAttributesDetails)
            )
            .satisfies(e -> assertThat(e.organizationStatus).as("check organizationStatus").isEqualTo(actual.organizationStatus))
            .satisfies(e -> assertThat(e.activationStatus).as("check activationStatus").isEqualTo(actual.activationStatus))
            .satisfies(e -> assertThat(e.logoImg).as("check logoImg").isEqualTo(actual.logoImg))
            .satisfies(e -> assertThat(e.logoImgContentType).as("check logoImg contenty type").isEqualTo(actual.logoImgContentType));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationUpdatableRelationshipsEquals(Organization expected, Organization actual) {
        assertThat(expected)
            .as("Verify Organization relationships")
            .satisfies(e -> assertThat(e.tenant).as("check tenant").isEqualTo(actual.tenant))
            .satisfies(e -> assertThat(e.typeOfOrganization).as("check typeOfOrganization").isEqualTo(actual.typeOfOrganization))
            .satisfies(e -> assertThat(e.organizationParent).as("check organizationParent").isEqualTo(actual.organizationParent));
    }
}
