package de.org.dexterity.azimuteerp.monolith.quarkus.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SupplierAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierAllPropertiesEquals(Supplier expected, Supplier actual) {
        assertSupplierAutoGeneratedPropertiesEquals(expected, actual);
        assertSupplierAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierAllUpdatablePropertiesEquals(Supplier expected, Supplier actual) {
        assertSupplierUpdatableFieldsEquals(expected, actual);
        assertSupplierUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierAutoGeneratedPropertiesEquals(Supplier expected, Supplier actual) {
        assertThat(expected)
            .as("Verify Supplier auto generated properties")
            .satisfies(e -> assertThat(e.id).as("check id").isEqualTo(actual.id));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierUpdatableFieldsEquals(Supplier expected, Supplier actual) {
        assertThat(expected)
            .as("Verify Supplier relevant properties")
            .satisfies(e -> assertThat(e.acronym).as("check acronym").isEqualTo(actual.acronym))
            .satisfies(e -> assertThat(e.companyName).as("check companyName").isEqualTo(actual.companyName))
            .satisfies(
                e -> assertThat(e.representativeLastName).as("check representativeLastName").isEqualTo(actual.representativeLastName)
            )
            .satisfies(
                e -> assertThat(e.representativeFirstName).as("check representativeFirstName").isEqualTo(actual.representativeFirstName)
            )
            .satisfies(e -> assertThat(e.jobTitle).as("check jobTitle").isEqualTo(actual.jobTitle))
            .satisfies(e -> assertThat(e.streetAddress).as("check streetAddress").isEqualTo(actual.streetAddress))
            .satisfies(e -> assertThat(e.houseNumber).as("check houseNumber").isEqualTo(actual.houseNumber))
            .satisfies(e -> assertThat(e.locationName).as("check locationName").isEqualTo(actual.locationName))
            .satisfies(e -> assertThat(e.city).as("check city").isEqualTo(actual.city))
            .satisfies(e -> assertThat(e.stateProvince).as("check stateProvince").isEqualTo(actual.stateProvince))
            .satisfies(e -> assertThat(e.zipPostalCode).as("check zipPostalCode").isEqualTo(actual.zipPostalCode))
            .satisfies(e -> assertThat(e.countryRegion).as("check countryRegion").isEqualTo(actual.countryRegion))
            .satisfies(e -> assertThat(e.webPage).as("check webPage").isEqualTo(actual.webPage))
            .satisfies(e -> assertThat(e.pointLocation).as("check pointLocation").isEqualTo(actual.pointLocation))
            .satisfies(
                e ->
                    assertThat(e.pointLocationContentType)
                        .as("check pointLocation contenty type")
                        .isEqualTo(actual.pointLocationContentType)
            )
            .satisfies(e -> assertThat(e.mainEmail).as("check mainEmail").isEqualTo(actual.mainEmail))
            .satisfies(e -> assertThat(e.landPhoneNumber).as("check landPhoneNumber").isEqualTo(actual.landPhoneNumber))
            .satisfies(e -> assertThat(e.mobilePhoneNumber).as("check mobilePhoneNumber").isEqualTo(actual.mobilePhoneNumber))
            .satisfies(e -> assertThat(e.faxNumber).as("check faxNumber").isEqualTo(actual.faxNumber))
            .satisfies(e -> assertThat(e.extraDetails).as("check extraDetails").isEqualTo(actual.extraDetails));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSupplierUpdatableRelationshipsEquals(Supplier expected, Supplier actual) {
        assertThat(expected)
            .as("Verify Supplier relationships")
            .satisfies(e -> assertThat(e.productsLists).as("check productsLists").isEqualTo(actual.productsLists));
    }
}
