apiVersion: v1
kind: ConfigMap
metadata:
  name: application-config
  namespace: azimuteerp-platform
#common configuration shared between all applications
data:
  application.yml: |-
    configserver:
      name: Consul
      status: Connected to Consul running in Kubernetes
    jhipster:
      security:
        authentication:
          jwt:
            base64-secret: MGM3NDllMjY4MzE0Yjk2MGFjMzBhY2M5YzhhZWExMDE0Y2RhMmRjNWFiNWRkMzI0Mzg5NWExNTQyNjk3YjBlMWYzMGI4Y2U3ZjcyMDk3ZWM5OWJjZjMyMTJiMjEzZDBiYmU3MQ==
  # app specific configuration
